# Generated by Django 4.2.4 on 2023-09-03 05:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('imageobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
