# Generated by Django 4.2.4 on 2023-09-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0002_alter_image_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
    ]
